### ISSUE TITLE
Computronics requires [computercraft@[1.80,)]

### ISSUE THREAD

**Issue by polyzium** [NoMansMinecraft/Computality#25]
Computronics requires CC and crashes with Computality. Probably we need sort of a wrapper for that...
```
[23:50:34] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.MissingModsException: Mod computronics (Computronics) requires [computercraft@[1.80,)]
Missing Mods:
        computercraft : [1.80,)


        at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:291) ~[Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:559) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[lh.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by TheCodedOne** [comment]
Computality's now changed its modid so computercraft addons will never work
