### ISSUE TITLE
No terminal text

### ISSUE THREAD

**Issue by IsaSca** [NoMansMinecraft/Computality#39]
All computers, turtles and other computality related mod items have absolutely no text. The only thing that appears is a blank screen.

**Comment by TheCodedOne** [comment]
minecraft version.. forge version.. computality version? like.. i cant help if you give no information

**Comment by IsaSca** [comment]
I am really sorry, I'm quite tired aha. Okay so I'm using computality 1.12.1 with forge 1.12.1 and I have biomes o plenty, cxlibrary, instant massive structures, journeyman, jei, mo bends, mo furnaces, optifine hd u c5 and treecapitator all installed under 1.12.1 too.

**Comment by IsaSca** [comment]
*journeymap

**Comment by TheCodedOne** [comment]
is it reproducible with just computality

**Comment by IsaSca** [comment]
Yes. Even with just computality running on a brand new world the terminal remains blank.

**Comment by IsaSca** [comment]
Update:

Completely uninstalled Minecraft, deleted .Minecraft, reinstalled it and reinstalled computality on its own and still no terminal text.

**Comment by Desidero** [comment]
For what it's worth, I'm running into the same problem on 1.12.1.

System info:
OS: Ubuntu 17.04 x64
Forge: 1.12.1-14.22.1.2485
Minecraft Server: 1.12.1
Computality: 1.12.1

There's a nullPointerException when initializing the filesystem. This shows up in the logs whenever I attempt to interact with a computer or turtle (removed the STDERR/timestamp stuff for readability):

```
computality: Error running task.
java.lang.NullPointerException
     at dan200.computality.core.filesystem.FileSystem.mountWritable(FileSystem.java:178)
     at dan200.computality.core.filesystem.FileSystem.<init>(FileSystem.java:26)
     at dan200.computality.core.computer.Computer.initFileSystem(Computer.java:255)
     at dan200.computality.core.computer.Computer.access$200(Computer.java:27)
     at dan200.computality.core.computer.Computer$1.execute(Computer.java:467)
     at dan200.computality.core.computer.ComputerThread$1$1.run(ComputerThread.java:92)
     at java.lang.Thread.run(Thread.java:748)
```

Unfortunately I don't see a way to increase the log level, so I can't troubleshoot more without hooking up a debugger or something. If there's anything else I can provide, let me know.

**Comment by TheCodedOne** [comment]
I'm currently away but i'll look into this before next month
